export const gallerySeed = [
  {
    id: "g-aurora",
    type: "photo",
    src: "/images/gallery/aurora.jpg",
    date: "2024-11-21T07:20:00Z",
    location: "Kyiv, UA",
    emotion: "happy",
    resonance: 0.86,
    tags: ["sunrise", "city", "calm"],
    linked_event: "calendar-walk-001",
    note: "Ранковий променад з кавою",
  },
  {
    id: "g-river",
    type: "video",
    src: "/images/gallery/river.mp4",
    date: "2024-10-05T16:45:00Z",
    location: "Dnipro River",
    emotion: "nostalgic",
    resonance: 0.73,
    tags: ["water", "family", "autumn"],
    linked_event: "calendar-family-015",
    note: "Відео з човна під час дощу",
  },
  {
    id: "g-workshop",
    type: "photo",
    src: "/images/gallery/workshop.jpg",
    date: "2024-09-14T12:10:00Z",
    location: "Lviv, Makerspace",
    emotion: "calm",
    resonance: 0.65,
    tags: ["workshop", "idea", "friends"],
    linked_event: null,
    note: "Перший прототип станції Cimeika",
  },
  {
    id: "g-midnight",
    type: "photo",
    src: "/images/gallery/midnight.jpg",
    date: "2024-12-28T23:50:00Z",
    location: "Kharkiv, UA",
    emotion: "neutral",
    resonance: 0.52,
    tags: ["city", "night"],
    linked_event: "calendar-newyear-001",
    note: "Тиха прогулянка під зимовим небом",
  },
];
